site_name: Docs 4admins
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Fira Mono
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: green
      accent: light-green

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: deep orange



markdown_extensions:
  - attri_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:pymdownx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/orgs/4admins

copyright: "Copyright 2026, 4admins"

plugins:
  - search

# nav:
#   - Home: index.md
#   - Getting Started: getting-started.md
#   - Guides:
#       - Installation: guides/installation.md
#       - Configuration: guides/configuration.md
#       - Usage: guides/usage.md
#   - API Reference: api.md
#   - FAQ: faq.md
#   - Contact: contact.md